---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:

    username: aquaman
    appPath: "/home/{{username}}/core"
    
    samba_netbios_name: SAMBA_TEST
    samba_server_string: 'Welcome to the test file server'
    samba_workgroup: WORKGROUP
    
    #samba_global_include: global-include.conf

    samba_load_homes: false
    samba_load_printers: false
    samba_create_varwww_symlinks: false

    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '

    # The smbclient version of the Travis CI environment crashes when `min
    # protocol' is set:
    #    protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
    # Uncomment the following lines if you want to test this setting locally.
    #
    # samba_server_min_protocol: SMB2
    # samba_server_max_protocol: SMB3

    samba_map_to_guest: Never
    samba_users:
      - name: {{username}}
        password: p@ssw0rd!
    #samba_username_map:
    #  - from: dev
    #    to: aquaman
    #the root + samba_shares\name dictates the full path
    samba_shares_root: /home
    samba_shares:
      - name: {{username}}
        comment: 'App Dev'
        public: 'yes'
        #group: root
        setype: public_content_t
        browseable: 'yes'
        writable: 'yes'
    nodejs_version: 10.x
    nodejs_package_json_path: {{appPath}}
    nodejs_npm_global_packages: [bonescript, nodemon]
  pre_tasks:
    - name: Ensure package database is up-to-date
      apt:
        update-cache: true
      failed_when: false
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create app user
      user:
        name: {{username}}
        groups: users,gpio
        append: true
        password: "$6$mysaltysalt$u2iN65Ch/LBvteyO.yVSqbgsuLpdB6HcET5qFrJIu1ZxTDrf/L88yDk4h1vXk1Sk7NWm5yRZKR.fNGK6CZmvr/"
    - name: clone app down
      git:
        repo: https://github.com/jrich523/AquaMan.git
        dest: {{appPath}}
      become: 'yes'
      become_user: {{username}}
    # https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
    - name: set max user watches for Nodemon (dev only)
      lineinfile: >
        create=yes
        dest=/etc/sysctl.d/60-user.conf
        group=root
        line="fs.inotify.max_user_watches = 524288"
        mode="0644"
        owner=root
        regexp="^fs.inotify.max_user_watches"
        state=present
    - name: Restart systemd
      service:
        name: systemd-sysctl
        state: restarted
  roles:
    - samba
    - nodejs
  tasks:
      # different service files for prod vs dev (node vs nodemon)
    - name: Create AquaMan Service
      template: src=service.j2 dest=/etc/systemd/system/aquaman.service
    - name: Start AquaMan
      systemd: state=started name=aquaman daemon_reload=yes enabled=yes
