---
- hosts: 127.0.0.1
  connection: local
  become: true
  pre_tasks:
    - name: Ensure package database is up-to-date
      apt:
        update-cache: true
      failed_when: false
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create app user
      user:
        name: aquaman
        groups: users,gpio
        append: true

  vars:
    samba_netbios_name: SAMBA_TEST
    samba_server_string: 'Welcome to the test file server'
    samba_workgroup: TESTGROUP
    
    samba_global_include: global-include.conf

    samba_load_homes: false
    samba_load_printers: false
    samba_create_varwww_symlinks: false

    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '

    # The smbclient version of the Travis CI environment crashes when `min
    # protocol' is set:
    #    protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
    # Uncomment the following lines if you want to test this setting locally.
    #
    # samba_server_min_protocol: SMB2
    # samba_server_max_protocol: SMB3

    samba_map_to_guest: Never
    samba_users:
      - name: dev
        password: p@ssw0rd!
    samba_username_map:
      - from: dev
        to: aquaman
    #the root + samba_shares\name dictates the full path
    samba_shares_root: /home
    samba_shares:
      - name: aquaman
        comment: 'App Dev'
        public: 'yes'
        #group: root
        setype: public_content_t
        browseable: 'yes'
        writable: 'yes'
  roles:
    - samba
  tasks:
    - name: clone app down
      git:
        repo: https://github.com/jrich523/AquaMan.git
        dest: /home/aquaman/core
